<?php

/**
 * @file
 * Contains view_formatter_layouts.module.
 */
use Drupal\view_formatter_layouts\ViewFormatterLayouts;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_help().
 */
function view_formatter_layouts_help($route_name, RouteMatchInterface $route_match)
{
	switch ($route_name) {
		// Main module help for the view_formatter_layouts module.
		case 'help.page.view_formatter_layouts' :
			$output = '';
			$output .= '<h3>' . t(' About ') . '</h3>';
			$output .= '<p>' . t(' formate la view via les layouts ') . '</p>';
			return $output;
		default :
	}
}

/**
 * Implements hook_theme().
 */
function view_formatter_layouts_theme()
{
	$hooks = ViewFormatterLayouts::getThemeHooks();
	$hooks['view_formatter_layouts'] = [
			'render element' => 'children'
	];
	return $hooks;
}

/**
 * Implements hook_preprocess_views_view__product_teaser().
 */
function view_formatter_layouts_preprocess_views_view__product_teaser(&$vars)
{
	$vars['attributes']['class'][] = 'row';
}


